
spring:

  datasource:

    url: jdbc:postgresql://127.0.0.1:5432/oa

    driver-class-name: org.postgresql.Driver

    username: postgres

    password: pisa1989[]

  jpa:

    database: postgresql

    show-sql: true

    hibernate:

      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

    properties:

      hibernate:

        temp:

          use_jdbc_metadata_defaults: false

graphql:

      servlet:

               mapping: /graphql

               enabled: true

               corsEnabled: true

graphiql:

    mapping: /graphiql

    endpoint: /graphql

    enabled: true

    pageTitle: GraphiQL
